apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:q7pulR1T7uF0iZn9kSu7PMon3Nj5wsLDDrL+FLChuo65oiTkp3nOAQ==,iv:WncCihEL6jsuU6Yo6SUO0yxsudUw4NUk24SlUctVnZw=,tag:b7hh9nfVxt4pQ4Z0h8KT5A==,type:str]
sops:
    age:
        - recipient: age1zffnskvuezntkk703a0pyxsd5m8vx2hm33dr47wdfy8mn4fdw4sqgw0jgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNm5BVXpUeXBsN2VLWDVk
            em9ET3VVMUJaQVY2RzlZMEpaUFJBaGs4YWdzCjFrYm5DQ2VGeGJ0WHdnODk5VWJF
            RnNleGhPT245c2dhckVnbTVwWFBjNWcKLS0tIEh5cnZiSTF5aWpham14MmliSXEy
            VEo5L25DNDF0c0hjYUxTek43ckxVRkEKmo/PLZTn8YtcWjFzDlwpUn7Y+Jyde0Cl
            z/mzEJDhjX2ozdLTQdZog8d0PVnzQ8DY47NumyIItYWyiDHDBfEm5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T11:32:15Z"
    mac: ENC[AES256_GCM,data:lgpjt+lAkz61ZubY4Gno//ZZmeigVCyMC8yt8+EdQHCCJhGjSnaWKpHuj6sa0df14nw2koTC8sPXP8Y2G+5ikJNBLGcJhl9ZR7cEG5tKjMUy367xamPKzRwDpv1U/OCEdpT4G6uDPWx5J3I8EfyYwC+NQpTgluJNjjnfX/ocGX0=,iv:bV0rECMs8wG10eCKxVU9WGVUDKc/XxS00YWvm4XTraw=,tag:uv1LpRXLJw882VfTBJ/a1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
