---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archmirror
  namespace: archmirror
  labels:
    app: archmirror
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: archmirror
  template:
    metadata:
      labels:
        app: archmirror
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/archlinux
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: archmirror-data
        - name: nginx-config
          configMap:
            name: archmirror-nginx-config
