---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archmirror-data-nfs
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${ARCHMIRROR_NFS_PATH}
