---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archmirror-data
  namespace: archmirror
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: archmirror-data-nfs
  resources:
    requests:
      storage: 200Gi
