apiVersion: v1
kind: PersistentVolume
metadata:
  name: grocy-config-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${GROCY_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: grocy-config-nfs
  resources:
    requests:
      storage: 5Gi
