apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-nginx-config
  namespace: blog
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        root /git/current;
        index index.html;

        location /health {
            access_log off;
            return 200 "OK";
            add_header Content-Type text/plain;
        }

        location ~ /\.git {
            deny all;
            return 404;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
