apiVersion: v1
kind: PersistentVolume
metadata:
  name: podsync-data-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${PODSYNC_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: podsync-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: /volume3/k8s-storage/podsync-database
