apiVersion: v1
kind: PersistentVolume
metadata:
  name: podsync-data-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nointr
  nfs:
    server: synology.storage.lviv
    path: ${PODSYNC_NFS_PATH}
