apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podsync-data
  namespace: podsync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: podsync-data-nfs
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podsync-database
  namespace: podsync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: podsync-database
  resources:
    requests:
      storage: 1Gi
