apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pihole-config
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pihole-dnsmasq
  resources:
    requests:
      storage: 1Gi
