apiVersion: v1
kind: Secret
metadata:
    name: pihole-credentials
    namespace: pihole
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:Sl3wOaQ=,iv:Dfxr5s97cMJHK0R+Ve6AzMFcLpl7ilV9Pq8RLSvQQHE=,tag:5u+8u1DBrU0Gazm/4JxIBQ==,type:str]
sops:
    age:
        - recipient: age1zffnskvuezntkk703a0pyxsd5m8vx2hm33dr47wdfy8mn4fdw4sqgw0jgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTE1tbzhLdkJpeXFOSHF3
            Nlk1Tm83UVdoZytuQ01yLzhJUlJPdVdEWkhzClJ6MkxvSVZmMkEwNWJYM0R3MGxP
            NHhsVElPTlJZeEZIakZGSWpXYWcvV2MKLS0tIGZPbkxvTDBnNVVKUk5YZXZOQVJ1
            dVRld2ZKdmdUNDgwZmpjeElvSXdydE0KZItCnGh6eHKJYtC5n5JLwLCfOWblh0iN
            4Q1O8uUXyz9EzTgY7CSAGpHo7N9pLznFr3AnOE4b2T5enDDnSK/tSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T10:40:42Z"
    mac: ENC[AES256_GCM,data:fEe5fEqgRtru1dZ/rVeDWIiT0sY4Or5z4AR8gzBDuBoF/lJQz86v32CoqhboMHl3EPdvZtteg2WBDU4LuwOHmhLf4qpvPX2KxL9rbe9ND3wP2PoEK/cMO7lqIKCVDOOz3OtdEcR7iT1XLr7wze1x4W9MjqLMqvcGplkRls77hlU=,iv:2JTEavm5ftNOU51dNG73RxpqahBNAsXlm+QHnlWt3Cc=,tag:YBmATtmbnsWGY3348Kz3/w==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
