apiVersion: v1
kind: PersistentVolume
metadata:
  name: lubelogger-data-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${LUBELOGGER_DATA_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-data
  namespace: lubelogger
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: lubelogger-data-nfs
  resources:
    requests:
      storage: 5Gi
