---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-data
  namespace: lubelogger
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-keys
  namespace: lubelogger
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 1Gi
