apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-data-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - intr
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${PAPERLESS_DATA_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: paperless-data-nfs
  resources:
    requests:
      storage: 10Gi
