apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${PAPERLESS_MEDIA_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-media-nfs
  resources:
    requests:
      storage: 100Gi
