apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 1Gi
