apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nointr
  nfs:
    server: synology.storage.lviv
    path: /volume3/k8s-storage/jellyfin-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nointr
  nfs:
    server: synology.storage.lviv
    path: /volume3/k8s-storage/jellyfin-cache
