apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nointr
  nfs:
    server: synology.storage.lviv
    path: ${MEDIA_NFS_PATH}
