apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-db
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: authelia-db
  resources:
    requests:
      storage: 2Gi
