apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: hyperhdr
  namespace: monitoring
  labels:
    app.kubernetes.io/name: hyperhdr
spec:
  jobName: hyperhdr
  targetEndpoints:
    - targets:
        - "hyperhdr.iot.lviv:9100"
      scheme: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 10s
      relabelConfigs:
        - targetLabel: instance
          replacement: hyperhdr
