apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 10Gi
