apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptpad-config
  namespace: cryptpad
data:
  application_config.js: |
    (() => {
    const factory = (AppConfig) => {
        AppConfig.registeredOnlyTypes = AppConfig.availablePadTypes;
        AppConfig.disableAnonymousPadCreation = true;
        AppConfig.disableAnonymousStore = true;

        return AppConfig;
    };
    
    
    if (typeof(module) !== 'undefined' && module.exports) {
        module.exports = factory(
            require('../www/common/application_config_internal.js')
        );
    } else if ((typeof(define) !== 'undefined' && define !== null) && (define.amd !== null)) {
        define(['/common/application_config_internal.js'], factory);
    }
    
    })();
  
  config.js: |
    module.exports = {
        httpUnsafeOrigin: 'https://${CRYPTPAD_HOST}',
        httpSafeOrigin: 'https://${CRYPTPAD_SANDBOX_HOST}',
        httpAddress: '0.0.0.0',
        //httpPort: 3000,
        //httpSafePort: 3001,
        // websocketPort: 3003,
        // maxWorkers: 4,
        //otpSessionExpiration: 7*24, // hours
        //enforceMFA: false,
        //logIP: false,
        adminKeys: [
          "[oleksandr@cryptpad.berezovskyi.dev/wiMN+oF1CaWHMaWxv11M+xqvnjXfNgshqoKIvEcG9Ss=]"
        ],
        //inactiveTime: 90, // days
        //archiveRetentionTime: 15,
        //accountRetentionTime: 365,
        //disableIntegratedEviction: true,
        //maxUploadSize: 20 * 1024 * 1024,
        //premiumUploadSize: 100 * 1024 * 1024,
        filePath: './datastore/',
        archivePath: './data/archive',
        pinPath: './data/pins',
        taskPath: './data/tasks',
        blockPath: './block',
        blobPath: './blob',
        blobStagingPath: './data/blobstage',
        decreePath: './data/decrees',
        logPath: './data/logs',
        logToStdout: true,
        logLevel: 'verbose',
        logFeedback: false,
        verbose: true,
        installMethod: 'docker',
    };