apiVersion: v1
kind: PersistentVolume
metadata:
  name: cryptpad-config-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${CRYPTPAD_CONFIG_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-config
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: cryptpad-config-nfs
  resources:
    requests:
      storage: 10Gi
