apiVersion: v1
kind: PersistentVolume
metadata:
  name: cryptpad-data-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${CRYPTPAD_DATA_NFS_PATH}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-data
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: cryptpad-data-nfs
  resources:
    requests:
      storage: 100Gi
