apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-onlyoffice
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
