apiVersion: v1
kind: Secret
metadata:
    name: cryptpad-credentials
    namespace: cryptpad
stringData:
    #ENC[AES256_GCM,data:s4VxDsDqwHw6ZhFNzA/mS+gdPwZlV5AcBDRUqfHTKSzjQPVg7unz7HkyfXtSBt36aH3P7fR9lUF1XtNvH9fF+6EfCa1dzIToSEw=,iv:TuYHrkjDFkA7fHhWzaHGrptyP5ClwiMArjoTf5LHXrQ=,tag:gvZxTmeeCEDTISgIpKxhhA==,type:comment]
    #ENC[AES256_GCM,data:CXpQCo8r5GCE6lIpXpXlab0CEdMCuNC54Ynh4ahfE1fv2c49wNoiQNRQAjONbmhUoUIiUcCehNmuw/ZK5Fd3rvVUhXdUAKYo,iv:U6vrAHUz22QWSLxBYRFea+LXajuHIh8NlggB6DAoCjc=,tag:nnV8RMrNv+trUQgXpCvkJA==,type:comment]
    #ENC[AES256_GCM,data:7TBFv3i2TzlyAcVhAdFE6T2F0E8pdAbYZorT6/brY8Ed+g6LvnwdVaYPcpJ7P6ETWXraqbhoktWICYklr35PAg==,iv:xsPinB1/gkzMHyzsrJ2gj8Fm0PWaIQbtBIB7fT1BTzI=,tag:O9dv+myneU7neE7JiRGuBQ==,type:comment]
    sso.js: ENC[AES256_GCM,data:3BO8v1Cay1nvkmYRVJp2aB2Kejn4+5R4uFwTKrnVrfc5MmBbcz9U7+/YHmLxKMsoaLWO9LZe6LwjLRK3DIPSRmKBXGPiZzH/PooVmDcKj3ujw5mJwI4ecDYERIuQF1V37OFBKLINE2J3aV+ZVI0hpGbdmQwtNK4eGP9oEEPjs6Lcdo1845BlZCfXhu16+lFeingeuG278BFNgjq+nS77M2rqqTxESjDV2Xxy42pcZDunXJgElk5QspsEK6ka49UlIYtHQWfsAVY32mR5FKsp/IaVScLXqOesCacWl6mZM9AwDuoqy5l43S16FXb0J+A+JWs7oVUXu+F40365ZYhBSjTgF9qRz4nBHnv+R2CGeLzma/R+lBAzVw4sKFivLXhHTlv64b2dE8ZkUsxfk4nALau2+usr4XhMjvRaFao2DwRElcyU5V3p9U89VjPvd/uk45lJQGye/6ZcnmmGjXw1IcRIQMvEN5KbGu1W7yPXafMG4+5WZq1luoJIgxsscRUbtyOOzn179DaQnC+8xVeac2eJYB9ZKe9/QnrfAn7lW7RfbUvAT2tfdiVbuhygRZTBKDNaxXp/2jxRZGv7QmwH9+lzaeFxaCuXVGJGJelWDr1BjJVizyTf5k5puXE93vAhMSx2xET/QFF/WHHuVG27LLq+01m5zNYRricolBk62Q1risLJUI/30dwXCVUdIpD7V3liNjnQ2HIwCh++DaJFM75j9QtM9Wt/TuNuCTug5u6cXgVvjGPZQCqMbrEl2uiprwQHB2ZdJrmGuielvPRy,iv:Mr+T088NwO9jSms3iYJW5KmAwWhJtzv0J5sSoUnDX9w=,tag:JbVuAu92I2wAkBpPpIwujg==,type:str]
sops:
    age:
        - recipient: age1zffnskvuezntkk703a0pyxsd5m8vx2hm33dr47wdfy8mn4fdw4sqgw0jgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Vm8xRmZ0WDJRMmNPVUxq
            T3VQSUVUYnVER0FFVW5FYWFHaUV3S2daWFJvCmxLdWpLVHpnMWNQaTlDZ0VOZ0JL
            K044cmpRZm50SmZNNWZlWjBDS1hGS2cKLS0tIGRxMnZTTWRRMlg5eVBOb3pVYUlK
            clRoWlp2SjQrOGFjQW92VnQ4amxUMXMKMjcBWo44X+Y2kmwpKZcBsBZZkWQJZEOf
            VscZUj8VAZKF9IxOmbBaFc2EBi5xI7sYJSJ+gaLHHKLhcSNu59P+kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T12:26:43Z"
    mac: ENC[AES256_GCM,data:9khTEFYbcN7LKs4PzL4f8hz8dibenAHnnXBfWa/FQCpL2vnrkSxuV/Qnsbur9xeWwALqD3gmHtmcfTZKkl5MJl2Kg7oL3TUV0WjtKuDPZN/irIonXlQ1u2GJ8N2+Tz+TqzV9545s3vUSH2Jl+CEnRJ2WQdFUXR6X4ufffsYPk4g=,iv:DN07fWrND7WHRbKiSxqLjfCPV7Sy+f1/4GdB3XTp0Qc=,tag:1RytDjoBsPr1g40XqtRY6Q==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
