---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 39.0.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1m0s
  values:
    deployment:
      strategy:
        type: Recreate
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
    service:
      type: ClusterIP
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
