apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - noatime
    - timeo=30
    - retrans=3
  nfs:
    server: synology.storage.lviv
    path: ${IMMICH_UPLOAD_NFS_PATH}
