apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-db
  resources:
    requests:
      storage: 10Gi
