apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-nfs
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: qbittorrent-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: prowlarr-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarr-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: radarr-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-db
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: prowlarr-db
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-db
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonarr-db
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-db
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: radarr-db
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology-ssd
  resources:
    requests:
      storage: 1Gi
