apiVersion: v1
kind: Secret
metadata:
    name: media-db-credentials
    namespace: media
stringData:
    SONARR_DB_USER: ENC[AES256_GCM,data:4hElKqu/,iv:FxKGg5gBSVi6wwp7Evz/BeU1HXgkBSjlk5RqLm65qws=,tag:DeCX+CgbNUJVkvTLu7uBoQ==,type:str]
    SONARR_DB_NAME: ENC[AES256_GCM,data:idbioCQ81Vd8oz4=,iv:uD2fJ/4ZANiEB/V1zH1nfLF20LVOCuh6Zzrb1KQeekc=,tag:/Cp0K2U488VBQdtJX3lvmQ==,type:str]
    SONARR_DB_PASSWORD: ENC[AES256_GCM,data:Ut+XErV4XN60lgiLGZ6XTWEXWgLF8NHkrUUXv4M2XFNsL0/DvL4qfCTKigCP8FR5ayBNhXAoF3cQ467WUFpvUA==,iv:hfN6h0lLqWd7uSc/EHsZwPT2sjSyF0Oyr1HpCDfWkV8=,tag:Idb2bMtM/4OezqL2ttN2CA==,type:str]
    RADARR_DB_USER: ENC[AES256_GCM,data:q8IuzrfO,iv:MVretLwHLhd5fsYYRa9jyq59ebcYdZB1flYWoBwrTII=,tag:+LV02NiQyd+T6mwqLzET5A==,type:str]
    RADARR_DB_NAME: ENC[AES256_GCM,data:VxtGKMV+LO/exOo=,iv:6RUjbk+/tw1GQYK4nqElhELo5lqgvYhR7gYZIaLDOlM=,tag:FGexxymrlwncNcVMOLZ8/Q==,type:str]
    RADARR_DB_PASSWORD: ENC[AES256_GCM,data:SB2AGVPdlhGGreSKUQ9fxJn1O6wyPMucy+knwWhQrxqyijzMgCJIYFRv8Gr3gpns3Zo1EvX1faxc/EfN19XSxw==,iv:SeqSpGuCTmN4V3V9AGWSD664Z2mMdZU9tWM2uTZYusM=,tag:xm9J4s5F8x8ulMualpJVtQ==,type:str]
    PROWLARR_DB_USER: ENC[AES256_GCM,data:dmBKcJZIwz0=,iv:NyNDm+gHnV2Su6X8RY+UaB+XlMBZr4xXGHLQ4olvWdA=,tag:DJadB86B/nKlYANy94VFoQ==,type:str]
    PROWLARR_DB_NAME: ENC[AES256_GCM,data:T8VDs9xevQva9W7xLQ==,iv:j9jjHjKISTgw/0yxyo6uDQxy69xJ+OwqTWRCNjQZEdk=,tag:4g0utJBDxIr6+oowv41Q2Q==,type:str]
    PROWLARR_DB_PASSWORD: ENC[AES256_GCM,data:nS2QPK5o3YEPROxyAmNjeKxkUFzbJ4bDqfYarbOLrQrtwaVtc2j2mt0Zfs4n3I7t8jncLECeLCFB8XVoWZjsgQ==,iv:xqdDgt7uv+2W6UT7cCrcL/hcFAZG4vUbwfRaTW/4E5M=,tag:Y2o5Ok4UJuulfvxSr26p9w==,type:str]
sops:
    age:
        - recipient: age1zffnskvuezntkk703a0pyxsd5m8vx2hm33dr47wdfy8mn4fdw4sqgw0jgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINHB0V21XRklkY2p5WGZE
            a0UxaDVRODZoZUtlYm1nR1lnLzdITlZrZG44CnhwRDVkS1lhSWsrNU5ObE5kSWl5
            bVZhZUt3NFIzdUdWYVZZTXV4d09mVGcKLS0tIHhrTUFvdDRKZ1NyZ2llaHZQTWhK
            ZVZmNzRlOVRnK1FBdTc1ZmU1bzNidU0KBP4sIZzuVn7PU17e09p6Td0sMG7K+NsQ
            AcvdVNFr6mOfivGn86Ao1R4xPE4ANqZfrNQCgIoKxsOQPcc13vOJbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T18:40:09Z"
    mac: ENC[AES256_GCM,data:LLkETSpyM+mq9mevqOD3uguZWRYZuMrs3xQsypZATOR3qDIB+K4z+azjBb23mbnSefQe2+LIm2pbel6fbMSrKO+CdfCrNfBypYb0jK99XIgBgfwQMKz/iuNiAAngCS9+UIcyQqim0FxDRwkdjpOcAL0LbCiNpfIsoUXNiNSRh7w=,iv:0Wln1COrZlR3mWRB0GMdhUsvzjZbBK2eJZR8RiMPwvs=,tag:crfppHbHiQtGiLS4A/f69w==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
