apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
  labels:
    app: renovate
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: renovate
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:39
              env:
                - name: RENOVATE_PLATFORM
                  value: github
                - name: RENOVATE_REPOSITORIES
                  value: '["berezovskyi-oleksandr/homelab"]'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: github-token
                - name: LOG_LEVEL
                  value: info
              resources:
                requests:
                  memory: 512Mi
                  cpu: 500m
                limits:
                  memory: 1Gi
