apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
stringData:
    gitea-token: ENC[AES256_GCM,data:rgJUYnLvlnha1q5VCU99OGXvAEME3t2RdyAtMVnzTTvVf2ux5nxWMg==,iv:5i+D8kM8P0HKOHkq3TDSkC6xzNz1juZWWGdC/uHcmZI=,tag:YkqTcBvFAozpkgl9sPeWxA==,type:str]
    github-com-token: ENC[AES256_GCM,data:OGYg/7LKtx2FTsKEUvrMf81VUTc9nRAvZN9YKwCiAwWQhc2IgAUdWQ==,iv:/2d3Kvu45L6a3BXxrClOY5376S3n28Sw1lyZ9QGsEjM=,tag:Wjp2+J53vRbqKmlQAe9Dvg==,type:str]
sops:
    age:
        - recipient: age1zffnskvuezntkk703a0pyxsd5m8vx2hm33dr47wdfy8mn4fdw4sqgw0jgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbms0RlovUkZSMXBRbzdQ
            VHhla0RVbW1jVFBUQjA5Tk9rNkQzSnlCMGhNCi9BbHNGMjdVZHB2T1o5S1J0bXQv
            R1lQUklQT2UrQWFSS3FUWFg4MXRqeWsKLS0tIHBUaGlUcHNPZzFPRk5mdk1BRGZT
            WFpEUzFtWkcyZ0ExSno5cTBIaU5ENmsKkGzvTtT0chu+B9XfDI2vRl5FXd46NWoh
            uADvff8Y3s0zwco7d4KiKQ3RNUnCQdThLBw/kJJSLf2012KgcGtwFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T09:04:27Z"
    mac: ENC[AES256_GCM,data:YENWAnnhT/cGliy1iQ6zVW1FM0TW1nsujstvl5seqO1VwiOXwj/oPkVBxg1E8r8tIV9/af6vY/yo05RkNUuSgB2jYfA/dPYL1knGzfDPPqo2hrDYWKnO3Mpnjpe5u263gIGB4elE/MM61cXLucb7NbW7G6n3vTkbTXxtjakJOOY=,iv:kHpYTrOGVG1lP7KhXrnf/bXKmes+SAIkwLfFxJR/zq0=,tag:lsiER37cfgFcgt1utUGAww==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
